### PR TITLE
Multi execute

### PR DESCRIPTION
**Pull request by silverslice**
I have tried to refactor `execute` method to perform multiple queries correctly (https://github.com/ruckus/ruckusing-migrations/issues/154). 
I've removed `split_query` method and implemented `multi_query` method in each adapter instead.

### CODE REVIEW

**Comment by ruckus** [comment]
Thank you @silverslice 

Hey @tunder would this help?

**Comment by ruckus** [comment]
Thank you so much!

**Comment by denodster** [comment]
Any word on when this goes live on composer?

**Comment by tunder** [comment]
It is live already. Just use "ruckusing/ruckusing-migrations": "dev-master" in your composer.json file

**Comment by ruckus** [comment]
Formally created `1.1.0` on packagist

**Pull request merged**
