### PR TITLE
Add Mysql 5.7 json support

### PR DESCRIPTION
**Pull request by bboure**
Add json support for mysql 5.7.

https://dev.mysql.com/doc/refman/5.7/en/json.html

### CODE REVIEW

**Comment by kevinc1984** [comment]
Wow. I had no idea MySQL supported the JSON type, and I've been using it 
everyday for 8 years! :D

**Comment by bboure** [comment]
This PR has been open for almost 4 years now without merging. I guess I'll close it

**Comment by ruckus** [comment]
Hi @bboure thanks for reaching out. I have not touched this project in many years and have essentially abandoned it. I don't have a PHP stack locally I could setup to test this PR. But a quick glance shows that it should work :)

If you want we can re-open and I'll accept the PR.

**Comment by bboure** [comment]
Thanks @ruckus for getting back. I have not used this project for a long time either, but we have been using [a fork at Vreasy](https://github.com/Vreasy/ruckusing-migrations) for years that included this change. It has been working great ever since. 

I'll reopen it if you want to merge it

Thanks.

**Comment by ruckus** [comment]
Thank you!

**Pull request merged**
